package lk.zmessenger.consumerwatchconsummer.domain;

// default package
// Generated Jan 9, 2013 12:02:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Categories generated by hbm2java
 */
public class Categories {
	@Expose
	@SerializedName("category_id")
	private Integer categoryId;
	@Expose
	@SerializedName("category_name")
	private String categoryName;
	@Expose
	@SerializedName("deleted")
	private Byte deleted;
	@Expose
	@SerializedName("added_by")
	private Integer addedBy;
	@Expose
	@SerializedName("added_date")
	private String addedDate;
	@Expose
	@SerializedName("edited_by")
	private Integer editedBy;
	@Expose
	@SerializedName("edited_date")
	private String editedDate;
	@Expose
	@SerializedName("image_url")
	private String imageUrl;

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	public Integer getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(Integer addedBy) {
		this.addedBy = addedBy;
	}

	public String getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(String addedDate) {
		this.addedDate = addedDate;
	}

	public Integer getEditedBy() {
		return this.editedBy;
	}

	public void setEditedBy(Integer editedBy) {
		this.editedBy = editedBy;
	}

	public String getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(String editedDate) {
		this.editedDate = editedDate;
	}

}
