package lk.zmessenger.consumerwatchconsummer.domain;

// Generated Feb 20, 2013 4:50:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * CompResponse generated by hbm2java
 */
public class CompResponse {

	@Expose
	@SerializedName("comp_response_id")
	private Integer compResponseId;

	@Expose
	@SerializedName("response")
	private String response;

	private Byte deleted;
	private Date addedDate;
	private Date editedDate;

	public Integer getCompResponseId() {
		return this.compResponseId;
	}

	public void setCompResponseId(Integer compResponseId) {
		this.compResponseId = compResponseId;
	}

	public String getResponse() {
		return this.response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

}
