package lk.zmessenger.consumerwatchconsummer.domain;

import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;
// default package
// Generated Jan 9, 2013 9:26:46 AM by Hibernate Tools 3.4.0.CR1

/**
 * Products generated by hbm2java
 */
@Table(name = "News")
public class News extends Model {

	@Column(name = "news")
	private String news;

	public String getNews() {
		return news;
	}

	public void setNews(String news) {
		this.news = news;
	}

}
