package lk.zmessenger.consumerwatchconsummer.domain;

import java.util.List;

import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// default package
// Generated Jan 9, 2013 9:26:46 AM by Hibernate Tools 3.4.0.CR1

/**
 * Products generated by hbm2java
 */
@Table(name = "Products")
public class Products extends Model {
	@Column(name = "product_id", unique = true, notNull = true)
	@Expose
	@SerializedName("product_id")
	private int productId;
	//@Column(name = "categories")
	@Expose
	@SerializedName("categories")
	private Categories categories;
	@Column(name = "product_name")
	@Expose
	@SerializedName("product_name")
	private String productName;
	//@Column(name = "service_code")
	@Expose
	@SerializedName("service_code")
	private Integer serviceCode;
	//@Column(name = "deleted")
	@Expose
	@SerializedName("deleted")
	private Byte deleted;
	//@Column(name = "addedBy")
	@Expose
	@SerializedName("added_by")
	private Integer addedBy;
	//@Column(name = "added_date")
	@Expose
	@SerializedName("added_date")
	private String addedDate;
	//@Column(name = "edited_by")
	@Expose
	@SerializedName("edited_by")
	private Integer editedBy;
	//@Column(name = "editedDate")
	@Expose
	@SerializedName("edited_date")
	private String editedDate;
	@Column(name = "image_url")
	@Expose
	@SerializedName("image_url")
	private String imageUrl;
	//@Column(name = "PriceSummery")
	@Expose
	@SerializedName("summary_details")
	private List<PriceSummery> summeryList;
	
	

	public List<PriceSummery> getSummeryList() {
		return summeryList;
	}

	public void setSummeryList(List<PriceSummery> summeryList) {
		this.summeryList = summeryList;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(Integer serviceCode) {
		this.serviceCode = serviceCode;
	}

	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	public Integer getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(Integer addedBy) {
		this.addedBy = addedBy;
	}

	public String getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(String addedDate) {
		this.addedDate = addedDate;
	}

	public Integer getEditedBy() {
		return this.editedBy;
	}

	public void setEditedBy(Integer editedBy) {
		this.editedBy = editedBy;
	}

	public String getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(String editedDate) {
		this.editedDate = editedDate;
	}

}
