package lk.zmessenger.consumerwatchconsummer.domain;

// default package
// Generated Jan 9, 2013 12:02:12 AM by Hibernate Tools 3.4.0.CR1

import com.google.gson.annotations.SerializedName;

/**
 * Users generated by hbm2java
 */
public class Users {

	@SerializedName("comp_user_id")
	private Integer compUserId;
	@SerializedName("mobile_number")
	private String mobileNumber;

	public Integer getCompUserId() {
		return compUserId;
	}

	public void setCompUserId(Integer compUserId) {
		this.compUserId = compUserId;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

}
